import type {
  Project,
  Invoice,
  Document,
  SupportTicket,
  Integration,
  License,
  BrandConfig,
  User,
} from "@/types";

export const mockUser: User = {
  id: "usr_001",
  name: "Alex Johnson",
  email: "alex@acmecorp.com",
  company: "Acme Corporation",
  avatarInitials: "AJ",
};

export const brandConfig: BrandConfig = {
  companyName: "NyxPortal",
  primaryColor: "#6366f1",
  secondaryColor: "#4f46e5",
  accentColor: "#818cf8",
  supportEmail: "support@nyxcollective.io",
  domain: "portal.nyxcollective.io",
};

export const mockProjects: Project[] = [
  {
    id: "prj_001",
    name: "Website Redesign",
    status: "active",
    description: "Complete overhaul of the corporate website with modern design and improved UX.",
    progress: 65,
    dueDate: "2026-06-30",
    milestones: [
      { id: "ms_001", title: "Design Mockups", status: "completed", dueDate: "2026-03-15" },
      { id: "ms_002", title: "Frontend Development", status: "in-progress", dueDate: "2026-05-01" },
      { id: "ms_003", title: "Backend Integration", status: "pending", dueDate: "2026-06-01" },
      { id: "ms_004", title: "QA & Launch", status: "pending", dueDate: "2026-06-30" },
    ],
  },
  {
    id: "prj_002",
    name: "CRM Implementation",
    status: "active",
    description: "Deploying and customizing a CRM solution for the sales team.",
    progress: 40,
    dueDate: "2026-08-15",
    milestones: [
      { id: "ms_005", title: "Requirements Gathering", status: "completed", dueDate: "2026-02-28" },
      { id: "ms_006", title: "System Configuration", status: "in-progress", dueDate: "2026-05-15" },
      { id: "ms_007", title: "Data Migration", status: "pending", dueDate: "2026-07-01" },
      { id: "ms_008", title: "Training & Rollout", status: "pending", dueDate: "2026-08-15" },
    ],
  },
  {
    id: "prj_003",
    name: "Brand Identity Package",
    status: "completed",
    description: "Full brand refresh including logo, color palette, and guidelines.",
    progress: 100,
    dueDate: "2026-03-01",
    milestones: [
      { id: "ms_009", title: "Brand Discovery", status: "completed", dueDate: "2026-01-15" },
      { id: "ms_010", title: "Logo Design", status: "completed", dueDate: "2026-02-01" },
      { id: "ms_011", title: "Style Guide", status: "completed", dueDate: "2026-02-20" },
      { id: "ms_012", title: "Asset Delivery", status: "completed", dueDate: "2026-03-01" },
    ],
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv_001",
    number: "INV-2026-0042",
    amount: 8500,
    currency: "USD",
    status: "unpaid",
    dueDate: "2026-04-30",
    issuedDate: "2026-04-01",
    description: "Website Redesign - Phase 2 (Frontend Development)",
  },
  {
    id: "inv_002",
    number: "INV-2026-0041",
    amount: 3200,
    currency: "USD",
    status: "paid",
    dueDate: "2026-03-31",
    issuedDate: "2026-03-01",
    description: "Brand Identity Package - Final Delivery",
  },
  {
    id: "inv_003",
    number: "INV-2026-0038",
    amount: 1500,
    currency: "USD",
    status: "overdue",
    dueDate: "2026-03-15",
    issuedDate: "2026-02-15",
    description: "CRM Implementation - Discovery & Planning",
  },
  {
    id: "inv_004",
    number: "INV-2026-0035",
    amount: 5000,
    currency: "USD",
    status: "paid",
    dueDate: "2026-02-28",
    issuedDate: "2026-02-01",
    description: "Website Redesign - Phase 1 (Design)",
  },
];

export const mockDocuments: Document[] = [
  {
    id: "doc_001",
    title: "Master Service Agreement",
    type: "contract",
    status: "signed",
    createdDate: "2026-01-10",
    signedDate: "2026-01-12",
    fileSize: "245 KB",
  },
  {
    id: "doc_002",
    title: "Website Redesign Proposal",
    type: "proposal",
    status: "signed",
    createdDate: "2026-02-05",
    signedDate: "2026-02-07",
    fileSize: "1.2 MB",
  },
  {
    id: "doc_003",
    title: "Non-Disclosure Agreement",
    type: "nda",
    status: "signed",
    createdDate: "2026-01-08",
    signedDate: "2026-01-09",
    fileSize: "98 KB",
  },
  {
    id: "doc_004",
    title: "CRM Implementation Statement of Work",
    type: "contract",
    status: "pending",
    createdDate: "2026-04-01",
    fileSize: "380 KB",
  },
  {
    id: "doc_005",
    title: "Q1 2026 Progress Report",
    type: "report",
    status: "signed",
    createdDate: "2026-04-01",
    signedDate: "2026-04-02",
    fileSize: "2.1 MB",
  },
];

export const mockTickets: SupportTicket[] = [
  {
    id: "tkt_001",
    subject: "Login issue with mobile app",
    status: "resolved",
    priority: "high",
    createdDate: "2026-03-28",
    updatedDate: "2026-03-30",
    category: "Technical Support",
  },
  {
    id: "tkt_002",
    subject: "Invoice INV-2026-0038 payment dispute",
    status: "in-progress",
    priority: "medium",
    createdDate: "2026-04-02",
    updatedDate: "2026-04-05",
    category: "Billing",
  },
  {
    id: "tkt_003",
    subject: "Request for additional user seats",
    status: "open",
    priority: "low",
    createdDate: "2026-04-05",
    updatedDate: "2026-04-05",
    category: "Account Management",
  },
  {
    id: "tkt_004",
    subject: "CRM data export not working",
    status: "open",
    priority: "urgent",
    createdDate: "2026-04-06",
    updatedDate: "2026-04-06",
    category: "Technical Support",
  },
];

export const mockIntegrations: Integration[] = [
  {
    id: "int_001",
    name: "Aegis Security",
    description: "Identity management, SSO, and access control for your organization.",
    status: "connected",
    icon: "🛡️",
    product: "aegis",
  },
  {
    id: "int_002",
    name: "Ledger Finance",
    description: "Invoice generation, payment processing, and financial reporting.",
    status: "connected",
    icon: "📒",
    product: "ledger",
  },
  {
    id: "int_003",
    name: "Scribe Documents",
    description: "Document creation, e-signatures, and contract management.",
    status: "connected",
    icon: "✍️",
    product: "scribe",
  },
  {
    id: "int_004",
    name: "Haven Support",
    description: "Help desk, ticketing, and customer support management.",
    status: "connected",
    icon: "🏠",
    product: "haven",
  },
  {
    id: "int_005",
    name: "Forge Projects",
    description: "Project management, milestones, and team collaboration tools.",
    status: "pending",
    icon: "⚒️",
    product: "forge",
  },
];

export const mockLicenses: License[] = [
  {
    id: "lic_001",
    product: "NyxPortal",
    plan: "Business",
    status: "active",
    seats: 25,
    usedSeats: 18,
    expiresDate: "2027-01-31",
    licenseKey: "NYX-PRTAL-BIZ-XXXX-XXXX-XXXX",
  },
  {
    id: "lic_002",
    product: "Aegis Security",
    plan: "Professional",
    status: "active",
    seats: 50,
    usedSeats: 32,
    expiresDate: "2027-01-31",
    licenseKey: "NYX-AEGIS-PRO-XXXX-XXXX-XXXX",
  },
  {
    id: "lic_003",
    product: "Ledger Finance",
    plan: "Standard",
    status: "active",
    seats: 10,
    usedSeats: 5,
    expiresDate: "2026-12-31",
    licenseKey: "NYX-LEDGR-STD-XXXX-XXXX-XXXX",
  },
  {
    id: "lic_004",
    product: "Scribe Documents",
    plan: "Enterprise",
    status: "active",
    seats: 100,
    usedSeats: 18,
    expiresDate: "2027-01-31",
    licenseKey: "NYX-SCRBE-ENT-XXXX-XXXX-XXXX",
  },
  {
    id: "lic_005",
    product: "Haven Support",
    plan: "Standard",
    status: "trial",
    seats: 5,
    usedSeats: 3,
    expiresDate: "2026-05-06",
    licenseKey: "NYX-HAVEN-TRL-XXXX-XXXX-XXXX",
  },
];
